[project]
name = "fastapi-ctx-gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nimrod Oren", email = "nimrodo@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
fastapi-ctx-gateway = "fastapi_ctx_gateway:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
